[project]
name = "align_documents"
version = "0.0.1"
requires-python = ">=3.11"
readme = "README.md"


dependencies = [
    "sentence-transformers>=4.1.0",
    "semchunk>=3.2.1",
    "tqdm>=4.67.1",
    "torch>=2.7.0",
    "rapidfuzz>=3.13.0",
    "pandas>=2.3.1",
    "jsonlines>=4.0.0",
    "gitpython==3.1.45",
    "pyarrow>=18.1.0,<19.0.0",
]


[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.2",
    "ruff>=0.12.3",
    "pandas_stubs>=2.3.1",
]

[project.scripts]
info = "align_documents.info:main"
align_all = "align_documents.align_all:main"

[project.optional-dependencies]
annotation = [
    "label-studio>=1.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pdm]
distribution = true
