data_dir = ""                             # Path to the directory containing documents to align 
output_dir = "output"                     # Path to the output directory where aligned docs will be stored
embedding_model = "NbAiLab/nb-sbert-base" # Sentence embedding model to use (local path or huggingface hub repo id)
embedding_dir = "embeddings"              # Directory to store/read sentence embeddings
log_level = "INFO"                        # Set the log level
batch_size = 32                           # Batch size for encoding sentences
aggregation_strategy = "cut-off"          # Aggregation strategy for sentence embeddings
match_threshold = 0.95                    # Threshold for matching documents
