name: Run pre-commit hooks on all files

on:
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '3.11'

      - name: Run pre-commit
        env:
          UV_PYPROJECT_DEV_DEPENDENCIES: '1'
        run: uv run pre-commit run --all-files
