name: Run pre-commit hooks on all files and run tests with pytest

on:
  pull_request:

permissions:
  contents: read

jobs:
  run-pre-commit-and-tests:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Install project dependencies 
        run: uv sync --locked --dev
      
      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

      - name: Run pytest 
        run: uv run pytest